###### Class com.daydreamer.wecatch.R is created by jadx
###### Class com.daydreamer.wecatch.R.anim is created by jadx
###### Class com.daydreamer.wecatch.R.animator is created by jadx
###### Class com.daydreamer.wecatch.R.attr is created by jadx
###### Class com.daydreamer.wecatch.R.bool is created by jadx
###### Class com.daydreamer.wecatch.R.color is created by jadx
###### Class com.daydreamer.wecatch.R.dimen is created by jadx
###### Class com.daydreamer.wecatch.R.drawable is created by jadx
###### Class com.daydreamer.wecatch.R.id is created by jadx
###### Class com.daydreamer.wecatch.R.integer is created by jadx
###### Class com.daydreamer.wecatch.R.interpolator is created by jadx
###### Class com.daydreamer.wecatch.R.layout is created by jadx
###### Class com.daydreamer.wecatch.R.menu is created by jadx
###### Class com.daydreamer.wecatch.R.mipmap is created by jadx
###### Class com.daydreamer.wecatch.R.plurals is created by jadx
###### Class com.daydreamer.wecatch.R.raw is created by jadx
###### Class com.daydreamer.wecatch.R.string is created by jadx
###### Class com.daydreamer.wecatch.R.style is created by jadx
###### Class com.daydreamer.wecatch.R.xml is created by jadx